@startuml

'https://plantuml.com/skinparam
'https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html
'java -jar plantuml.jar -language

skinparam shadowing false
skinparam classFontSize 16
skinparam classStereotypeFontSize 14
'skinparam monochrome reverse
'skinparam classFontColor red
'skinparam classFontName Aapex


  App --- Game
  App --- MainHeader
  App --- Footer

  Game *--- QuestionHeader 
  Game *--- AnswersList
  Game *--- GameControls
  Game *--- GameProgressBar

  class App <component> {}

  class MainHeader <component> {
    + title:string
    + lead:string 
  }

  class QuestionHeader <component> {
    + question:string
    + difficulty:string
    + category:string
  }

  class Game <component>
  class GameControls <component>
  class GameProgressBar <component>
  class AnswersList <component>
@enduml